//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ESFRAMEWORK.rc
//
#define ID_OPTIONS_EXIT                 2
#define IDDEFAULT                       3
#define ID_ADDKF                        3
#define ID_WRITEKF                      4
#define ID_UPDATE                       5
#define ID_VIEWPORT                     6
#define IDD_SETUP                       101
#define IDI_APPICON                     103
#define IDD_DIALOG                      105
#define IDD_KEYFRAMELST                 106
#define IDD_LOADCAMERAPATH              107
#define IDD_LOADCAMERAFILE              108
#define IDD_SAVECAMERAFILE              109
#define IDI_ICON1                       113
#define IDD_OPTIONS                     119
#define IDB_BITMAP1                     124
#define IDC_SC320                       1002
#define IDC_SC512                       1002
#define IDC_SC640                       1003
#define IDC_SC800                       1004
#define IDC_SC1024                      1005
#define IDC_SC1280                      1006
#define IDC_SC1600                      1007
#define IDC_NOVSYNC                     1008
#define IDC_FULLSCREEN                  1009
#define IDC_LIST1                       1010
#define IDC_HEIGHTMAP                   1010
#define IDC_CAMERAFILESLIST             1010
#define IDC_EDIT2                       1012
#define IDC_HEIGHT_SCALING              1012
#define IDC_KFNUMBER                    1012
#define IDC_EDIT3                       1013
#define IDC_GRID_SIZE                   1013
#define IDC_KFTIME                      1013
#define IDC_RADIO7                      1014
#define IDC_TX64                        1014
#define IDC_KFLASTTIME                  1014
#define IDC_RADIO8                      1015
#define IDC_TX256                       1015
#define IDC_RADIO9                      1016
#define IDC_TX512                       1016
#define IDC_RADIO10                     1017
#define IDC_TX1024                      1017
#define IDC_RADIO11                     1018
#define IDC_TX2048                      1018
#define IDC_RADIO12                     1019
#define IDC_TX128                       1019
#define IDC_CHECK3                      1020
#define IDC_DETAIL_TEXTURE              1020
#define IDC_EDIT1                       1021
#define IDC_DT_TILING                   1021
#define IDC_ROTX                        1021
#define IDC_SAVEFILENAME                1021
#define IDC_ROTY                        1022
#define IDC_RADIO13                     1023
#define IDC_WD_LOW                      1023
#define IDC_ROTZ                        1023
#define IDC_RADIO14                     1024
#define IDC_WD_MID                      1024
#define IDC_POSX                        1024
#define IDC_RADIO15                     1025
#define IDC_WD_HIGH                     1025
#define IDC_POSY                        1025
#define IDC_RADIO16                     1026
#define IDC_WS_LOW                      1026
#define IDC_POSZ                        1026
#define IDC_RADIO17                     1027
#define IDC_WS_MID                      1027
#define IDC_RADIO18                     1028
#define IDC_WS_HIGH                     1028
#define IDC_EDIT4                       1029
#define IDC_WAVE_HEIGHT                 1029
#define IDC_STATUS                      1029
#define IDC_CHECK4                      1030
#define IDC_HSR                         1030
#define IDC_EDIT5                       1031
#define IDC_MAX_TRI_IN_NODE             1031
#define IDC_EDIT6                       1032
#define IDC_MIN_NODE_SIZE               1032
#define IDC_CHECK5                      1033
#define IDC_DRAW_NODES                  1033
#define IDC_CHECK6                      1034
#define IDC_SHADOWS                     1034
#define IDC_EDIT7                       1035
#define IDC_AMBIENT                     1035
#define IDC_CHECK7                      1036
#define IDC_DRAW_WATER                  1036
#define IDC_CHECK8                      1037
#define IDC_DRAW_SUN_FLARE              1037
#define IDC_EDIT8                       1038
#define IDC_SUN_HEIGHT                  1038
#define IDC_SUN_SIZE                    1039
#define IDREADME                        1040
#define IDC_FOV                         1041
#define IDC_NEAR                        1042
#define IDC_FAR                         1043
#define IDC_CROSSHAIR                   1044
#define IDC_STATISTICS                  1045
#define IDC_USE_CVA                     1047
#define ID_SAVE                         1048
#define ID_EXIT                         1049
#define IDC_SLIDER                      1050
#define ID_PLAY                         1050
#define ID_STOP                         1051
#define IDC_STATICFRM                   1052
#define IDC_STATICPRMTS                 1053
#define ID_LOAD                         1054
#define ID_REW                          1055
#define ID_FORW                         1056
#define IDC_FROMKF                      1060
#define IDC_TOKF                        1061
#define IDC_FRAMELIST                   1062
#define ID_PREVIEW                      1063
#define IDC_LOADCAMERAFILE              1064
#define ID_INSERTKF                     1064
#define IDC_LCREFRESH                   1065
#define ID_CLEARKF                      1065
#define ID_DELETEKF                     1066
#define IDC_SAVECAMERAFILE              1067
#define ID_MOVEDOWN                     1067
#define IDC_SAVEDCAMERAFILESLIST        1068
#define ID_MOVEUP                       1068
#define IDC_LINEAR                      1070
#define IDC_EASED                       1071
#define IDC_NONE                        1072
#define IDC_640x480                     1075
#define IDC_800x600                     1076
#define IDC_1024x768                    1077
#define IDC_OPTIONS_NOSOUND             1078
#define ID_OPTIONS_START                1079
#define IDC_OPTIONS_SHOWFPS             1080
#define IDC_PROGRESS1                   1081

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1082
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
